const $ = (s, p = document) => p.querySelector(s);
const esc = (value = '') => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let data, gallery = [], activeImage = 0, audio, touchX = 0;
const toast = message => { const el = $('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 2200); };
const dday = iso => { const wedding = new Date(iso); if (Number.isNaN(wedding)) return ''; const now = new Date(); const inKorea = d => new Date(d.toLocaleString('en-US', {timeZone:'Asia/Seoul'})); const a = inKorea(now); const b = inKorea(wedding); a.setHours(0,0,0,0); b.setHours(0,0,0,0); const days = Math.round((b-a)/86400000); return days === 0 ? 'D-DAY' : days > 0 ? `D-${days}` : `D+${Math.abs(days)}`; };
function page(d) { const w = d.wedding || {}, c = d.couple || {}, invitation = d.invitation || {}; gallery = d.gallery || []; return `
<header class="hero"><div class="hero-illustration"><img src="${esc(d.hero?.image)}" alt="${esc(d.hero?.alt)}" onerror="this.parentElement.classList.add('image-error')"></div><div class="hero-copy"><p class="hero-venue">${esc(w.venue)}</p><p class="hero-hall">${esc(w.hall)}</p><p class="hero-date">${esc(w.displayDate)} ${esc(w.day || '').slice(0,1).toUpperCase()} · ${esc(w.time)}</p></div></header>
<section class="section invitation reveal"><p class="section-label">${esc(invitation.label)}</p><h2>${esc(invitation.title)}</h2><div class="prose">${(invitation.paragraphs || []).map(p=>`<p>${esc(p)}</p>`).join('')}</div></section>
<section class="section story reveal"><p class="section-label">OUR STORY</p><h2>우리의 시간</h2><ol class="timeline">${(d.story || []).map(x=>`<li><time>${esc(x.year)}</time><div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p></div></li>`).join('')}</ol></section>
<section class="section gallery-section reveal"><p class="section-label">GALLERY</p><h2>우리의 순간</h2><div class="gallery">${gallery.map((x,i)=>`<button class="gallery-item" data-index="${i}" aria-label="${i+1}번째 사진 크게 보기"><img src="${esc(x.src)}" alt="${esc(x.alt)}" loading="lazy"></button>`).join('')}</div></section>
<section class="section info reveal"><p class="section-label">WEDDING DAY</p><h2>${esc(w.displayDate)}<br>${esc(w.day)} ${esc(w.time)}</h2><div class="info-place"><b>${esc(w.venue)}</b><span>${esc(w.hall)}</span><p>${esc(w.address)}</p></div></section>
<section class="section location reveal"><p class="section-label">LOCATION</p><h2>오시는 길</h2><img class="map" src="${esc(d.location?.mapImage)}" alt="${esc(d.location?.mapAlt)}" loading="lazy"><p class="address">${esc(w.address)}</p><div class="link-row"><a href="${esc(d.location?.mapUrl || '#')}" target="_blank" rel="noopener">지도 보기</a><a href="${esc(d.location?.directionsUrl || '#')}" target="_blank" rel="noopener">길찾기</a></div><div class="transit">${(d.location?.transit || []).map(x=>`<p><b>${esc(x.label)}</b><span>${esc(x.text)}</span></p>`).join('')}</div></section>
<section class="section accounts reveal"><p class="section-label">WITH LOVE</p><h2>마음 전하실 곳</h2><div class="account-list">${(d.accounts || []).map((group,groupIndex)=>`<details class="account-group"><summary><span>${esc(group.side)}</span><small>계좌번호 보기</small></summary><div class="account-items">${(group.accounts || []).map((account,accountIndex)=>`<article class="account-item"><button class="copy-button" data-group="${groupIndex}" data-account="${accountIndex}" aria-label="${esc(account.relation)} 계좌번호 복사">⧉</button><div><h3>${esc(account.relation)}</h3><p>${esc(account.bank)} <b>${esc(account.number)}</b></p><p>예금주 ${esc(account.holder)}</p></div></article>`).join('')}</div></details>`).join('')}</div></section>
<section class="section guestbook reveal"><p class="section-label">GUESTBOOK</p><h2>축하의 마음을<br>남겨주세요</h2><p>정성스러운 마음으로 준비 중인 공간입니다.</p><button id="guestbookButton" class="outline-button">축하 메시지 남기기</button></section>
<footer class="thanks reveal"><span>Thank you for celebrating with us</span><h2>${esc(c.groom)} <i>&amp;</i> ${esc(c.bride)}</h2><p>${esc(w.displayDate)}</p></footer>`; }
function openLightbox(index) { if (!gallery.length) return; activeImage = (index + gallery.length) % gallery.length; const item = gallery[activeImage]; $('#lightboxImage').src = item.src; $('#lightboxImage').alt = item.alt; $('#lightboxCount').textContent = `${activeImage + 1} / ${gallery.length}`; $('#lightbox').classList.add('open'); $('#lightbox').setAttribute('aria-hidden','false'); document.body.classList.add('locked'); $('.lightbox-close').focus(); }
function closeLightbox() { $('#lightbox').classList.remove('open'); $('#lightbox').setAttribute('aria-hidden','true'); document.body.classList.remove('locked'); }
function setup(d) { $('#app').innerHTML = page(d); document.title = `${d.couple?.groom || '신랑'} & ${d.couple?.bride || '신부'}의 결혼식 초대`; const observer = new IntersectionObserver(entries => entries.forEach(e => { if(e.isIntersecting) { e.target.classList.add('visible'); observer.unobserve(e.target); }}), {threshold:.12,rootMargin:'0px 0px -6%'}); document.querySelectorAll('.reveal').forEach((e,i) => { e.style.setProperty('--reveal-delay', `${Math.min(i % 3, 2) * 70}ms`); observer.observe(e); }); document.querySelectorAll('.gallery-item').forEach(b => b.addEventListener('click', () => openLightbox(+b.dataset.index))); document.querySelectorAll('.copy-button').forEach(b => b.addEventListener('click', async () => { const item = d.accounts?.[+b.dataset.group]?.accounts?.[+b.dataset.account]; const text = item?.number; if (!text) return toast('복사할 계좌번호가 없습니다.'); try { if (navigator.clipboard?.writeText) await navigator.clipboard.writeText(text); else { const t=document.createElement('textarea');t.value=text;document.body.append(t);t.select();document.execCommand('copy');t.remove(); } toast(`${item.relation || '계좌번호'} 계좌를 복사했어요.`); } catch { toast('복사하지 못했습니다. 다시 시도해 주세요.'); }})); $('#guestbookButton').addEventListener('click', ()=>toast('방명록은 따뜻하게 준비 중이에요.')); setupAudio(d.music); }
function setupAudio(music) { const btn = $('#musicButton'); if (!music?.enabled || !music.src) { btn.hidden = true; return; } audio = new Audio(music.src); audio.loop = true; audio.volume = .35; const update = playing => { btn.textContent = playing ? 'Ⅱ' : '♪'; btn.setAttribute('aria-label', playing ? '배경 음악 일시 정지' : '배경 음악 재생'); btn.setAttribute('aria-pressed', playing); }; audio.addEventListener('play',()=>update(true)); audio.addEventListener('pause',()=>update(false)); audio.addEventListener('error',()=>{btn.hidden=true;}); audio.play().catch(()=>update(false)); btn.addEventListener('click',()=> audio.paused ? audio.play().catch(()=>toast('음악을 재생할 수 없습니다.')) : audio.pause()); }
$('#shareButton').addEventListener('click', async () => { const w=data?.wedding || {}, title=`${data?.couple?.groom || '신랑'} & ${data?.couple?.bride || '신부'}의 결혼식에 초대합니다`, text=`${w.displayDate || ''}, 저희 결혼합니다.`; try { if(navigator.share) await navigator.share({title,text,url:location.href}); else if(navigator.clipboard?.writeText) { await navigator.clipboard.writeText(location.href); toast('청첩장 주소를 복사했어요.'); } else { prompt('아래 주소를 복사해 주세요.',location.href); } } catch(e) { if(e.name !== 'AbortError') toast('공유를 완료하지 못했습니다.'); }});
$('.lightbox-close').addEventListener('click',closeLightbox); $('.lightbox-prev').addEventListener('click',()=>openLightbox(activeImage-1)); $('.lightbox-next').addEventListener('click',()=>openLightbox(activeImage+1)); $('#lightbox').addEventListener('click',e=>{if(e.target.id==='lightbox') closeLightbox()}); document.addEventListener('keydown',e=>{if(!$('#lightbox').classList.contains('open')) return; if(e.key==='Escape')closeLightbox(); if(e.key==='ArrowLeft')openLightbox(activeImage-1); if(e.key==='ArrowRight')openLightbox(activeImage+1);}); $('#lightbox').addEventListener('touchstart',e=>touchX=e.changedTouches[0].screenX,{passive:true}); $('#lightbox').addEventListener('touchend',e=>{const dx=e.changedTouches[0].screenX-touchX;if(Math.abs(dx)>45)openLightbox(activeImage+(dx>0?-1:1));},{passive:true});
fetch('data/wedding.json').then(r=>{if(!r.ok) throw Error(); return r.json();}).then(d=>{data=d;setup(d);}).catch(()=>$('#app').innerHTML='<div class="loading">초대장 정보를 불러오지 못했습니다.</div>');
